"""phase4_backoffice_contract_captable_fund

Revision ID: 164c335b7a24
Revises: bccabceb7251
Create Date: 2026-03-17 01:09:35.607444
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '164c335b7a24'
down_revision: Union[str, None] = 'bccabceb7251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
