"""phase5_9_incubation_oi_meeting_kpi_sop_jd

Revision ID: 4704b8a343d4
Revises: 164c335b7a24
Create Date: 2026-03-17 04:07:26.614120
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '4704b8a343d4'
down_revision: Union[str, None] = '164c335b7a24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Pre-create enum types that don't exist yet (skip existing ones)
meetingtype = postgresql.ENUM('WEEKLY_DEAL', 'WEEKLY_PORTFOLIO', 'MONTHLY_OPS', 'IC', 'MENTORING', 'PARTNER_REVIEW', 'RISK_REVIEW', 'PROGRAM_OPS', name='meetingtype', create_type=False)
exittype = postgresql.ENUM('SECONDARY_SALE', 'MA', 'STRATEGIC_SALE', 'IPO', 'SECONDARY_MARKET', 'TECH_TRANSFER', 'JV', 'WRITEOFF', name='exittype', create_type=False)
portfoliograde = postgresql.ENUM('A', 'B', 'C', 'D', name='portfoliograde', create_type=False)
pocstatus = postgresql.ENUM('DEMAND_IDENTIFIED', 'MATCHING', 'PLANNING', 'KICKOFF', 'IN_PROGRESS', 'MID_REVIEW', 'COMPLETED', 'COMMERCIAL_CONTRACT', 'JOINT_DEVELOPMENT', 'STRATEGIC_INVESTMENT', 'RETRY', 'TERMINATED', name='pocstatus', create_type=False)
contractstatus = postgresql.ENUM('IC_RECEIVED', 'TERM_SHEET', 'LEGAL_REVIEW', 'SIGNING', 'DISBURSEMENT', 'COMPLETED', 'POST_FILING', name='contractstatus', create_type=False)
investmentvehicle = postgresql.ENUM('COMMON_STOCK', 'PREFERRED_STOCK', 'RCPS', 'CONVERTIBLE_NOTE', 'SAFE', 'DIRECT', 'INDIVIDUAL_UNION', 'VENTURE_FUND', name='investmentvehicle', create_type=False)


def upgrade() -> None:
    # Create enum types that don't exist yet
    conn = op.get_bind()
    for enum_name, enum_obj in [
        ('meetingtype', meetingtype), ('exittype', exittype),
        ('pocstatus', pocstatus), ('contractstatus', contractstatus),
        ('investmentvehicle', investmentvehicle),
    ]:
        result = conn.execute(sa.text(f"SELECT 1 FROM pg_type WHERE typname = '{enum_name}'"))
        if not result.fetchone():
            enum_obj.create(conn, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('form_code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owning_team', sa.String(length=50), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_code')
    )
    op.create_table('funds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fund_name', sa.String(length=200), nullable=False),
    sa.Column('fund_type', sa.String(length=30), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('committed_amount', sa.Integer(), nullable=False),
    sa.Column('deployed_amount', sa.Integer(), nullable=False),
    sa.Column('remaining_amount', sa.Integer(), nullable=False),
    sa.Column('formation_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('gp_entity', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_descriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('jd_code', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('team', sa.String(length=50), nullable=False),
    sa.Column('reports_to', sa.String(length=100), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('core_responsibilities', sa.JSON(), nullable=False),
    sa.Column('daily_tasks', sa.JSON(), nullable=False),
    sa.Column('weekly_tasks', sa.JSON(), nullable=False),
    sa.Column('monthly_tasks', sa.JSON(), nullable=False),
    sa.Column('quarterly_annual_tasks', sa.JSON(), nullable=True),
    sa.Column('collaboration_teams', sa.JSON(), nullable=False),
    sa.Column('deliverables', sa.JSON(), nullable=False),
    sa.Column('kpi_quantitative', sa.JSON(), nullable=False),
    sa.Column('kpi_qualitative', sa.JSON(), nullable=True),
    sa.Column('required_skills', sa.JSON(), nullable=False),
    sa.Column('preferred_qualifications', sa.JSON(), nullable=False),
    sa.Column('authority_scope', sa.JSON(), nullable=False),
    sa.Column('approval_required', sa.JSON(), nullable=False),
    sa.Column('responsibility_scope', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jd_code')
    )
    op.create_table('partner_demands',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('partner_company', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('demand_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tech_requirements', sa.Text(), nullable=True),
    sa.Column('timeline', sa.String(length=100), nullable=True),
    sa.Column('budget_range', sa.String(length=50), nullable=True),
    sa.Column('nda_required', sa.Boolean(), nullable=False),
    sa.Column('candidate_startups', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sop_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_number', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('revision_date', sa.Date(), nullable=True),
    sa.Column('owning_team', sa.String(length=50), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('required_forms', sa.JSON(), nullable=False),
    sa.Column('checkpoints', sa.JSON(), nullable=False),
    sa.Column('exception_rules', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_number')
    )
    op.create_table('demo_days',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('invited_investors', sa.JSON(), nullable=True),
    sa.Column('startup_readiness', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('follow_up_deadline', sa.Date(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fund_lps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fund_id', sa.Uuid(), nullable=False),
    sa.Column('lp_name', sa.String(length=200), nullable=False),
    sa.Column('lp_type', sa.String(length=30), nullable=False),
    sa.Column('committed_amount', sa.Integer(), nullable=False),
    sa.Column('paid_in_amount', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_lps_fund_id'), 'fund_lps', ['fund_id'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meeting_type', meetingtype, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('attendees', sa.JSON(), nullable=False),
    sa.Column('agenda_items', sa.JSON(), nullable=False),
    sa.Column('minutes', sa.Text(), nullable=True),
    sa.Column('action_items', sa.JSON(), nullable=True),
    sa.Column('related_startup_ids', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_kpis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('kpi_layer', sa.String(length=20), nullable=False),
    sa.Column('kpi_name', sa.String(length=100), nullable=False),
    sa.Column('kpi_definition', sa.Text(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('achievement_rate', sa.Float(), nullable=True),
    sa.Column('mom_change', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team', 'period', 'kpi_name', name='uq_team_kpi_period_name')
    )
    op.create_table('cap_table_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('shareholder_name', sa.String(length=200), nullable=False),
    sa.Column('share_type', sa.String(length=30), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('ownership_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('investment_amount', sa.Integer(), nullable=True),
    sa.Column('investment_date', sa.Date(), nullable=True),
    sa.Column('round_name', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cap_table_entries_startup_id'), 'cap_table_entries', ['startup_id'], unique=False)
    op.create_table('exit_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('exit_type', exittype, nullable=False),
    sa.Column('exit_amount', sa.Integer(), nullable=True),
    sa.Column('multiple', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('cap_table_clean', sa.Boolean(), nullable=False),
    sa.Column('preferred_terms_reviewed', sa.Boolean(), nullable=False),
    sa.Column('drag_tag_reviewed', sa.Boolean(), nullable=False),
    sa.Column('ip_ownership_clean', sa.Boolean(), nullable=False),
    sa.Column('accounting_transparent', sa.Boolean(), nullable=False),
    sa.Column('customer_contracts_stable', sa.Boolean(), nullable=False),
    sa.Column('management_issue_clear', sa.Boolean(), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exit_records_startup_id'), 'exit_records', ['startup_id'], unique=False)
    op.create_table('follow_on_investments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('round_type', sa.String(length=50), nullable=False),
    sa.Column('target_amount', sa.Integer(), nullable=True),
    sa.Column('investor_map', sa.JSON(), nullable=True),
    sa.Column('matching_criteria', sa.JSON(), nullable=True),
    sa.Column('lead_investor', sa.String(length=200), nullable=True),
    sa.Column('co_investors', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('ir_meetings_count', sa.Integer(), nullable=False),
    sa.Column('closed_at', sa.Date(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_on_investments_startup_id'), 'follow_on_investments', ['startup_id'], unique=False)
    op.create_table('form_submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('form_template_id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=True),
    sa.Column('submitted_by', sa.Uuid(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['form_template_id'], ['form_templates.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('government_programs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('program_type', sa.String(length=50), nullable=False),
    sa.Column('program_name', sa.String(length=200), nullable=False),
    sa.Column('managing_agency', sa.String(length=200), nullable=False),
    sa.Column('applied_at', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('our_role', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_government_programs_startup_id'), 'government_programs', ['startup_id'], unique=False)
    op.create_table('incubations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_pm_id', sa.Uuid(), nullable=False),
    sa.Column('program_start', sa.Date(), nullable=False),
    sa.Column('program_end', sa.Date(), nullable=False),
    sa.Column('diagnosis', sa.JSON(), nullable=True),
    sa.Column('action_plan', sa.JSON(), nullable=True),
    sa.Column('growth_bottleneck', sa.Text(), nullable=True),
    sa.Column('portfolio_grade', portfoliograde, nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('crisis_flags', sa.JSON(), nullable=True),
    sa.Column('onboarding_checklist', sa.JSON(), nullable=True),
    sa.Column('ir_readiness', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_pm_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incubations_startup_id'), 'incubations', ['startup_id'], unique=False)
    op.create_table('investor_meetings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('demo_day_id', sa.Uuid(), nullable=True),
    sa.Column('investor_name', sa.String(length=100), nullable=False),
    sa.Column('investor_company', sa.String(length=200), nullable=False),
    sa.Column('investor_type', sa.String(length=50), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('meeting_type', sa.String(length=50), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('materials_sent', sa.JSON(), nullable=True),
    sa.Column('next_step', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['demo_day_id'], ['demo_days.id'], ),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investor_meetings_startup_id'), 'investor_meetings', ['startup_id'], unique=False)
    op.create_table('kpi_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('revenue', sa.Integer(), nullable=True),
    sa.Column('customer_count', sa.Integer(), nullable=True),
    sa.Column('active_users', sa.Integer(), nullable=True),
    sa.Column('poc_count', sa.Integer(), nullable=True),
    sa.Column('repurchase_rate', sa.Float(), nullable=True),
    sa.Column('release_velocity', sa.String(length=100), nullable=True),
    sa.Column('cac', sa.Integer(), nullable=True),
    sa.Column('ltv', sa.Integer(), nullable=True),
    sa.Column('pilot_conversion_rate', sa.Float(), nullable=True),
    sa.Column('mou_to_contract_rate', sa.Float(), nullable=True),
    sa.Column('headcount', sa.Integer(), nullable=True),
    sa.Column('runway_months', sa.Float(), nullable=True),
    sa.Column('follow_on_meetings', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('startup_id', 'period', name='uq_kpi_startup_period')
    )
    op.create_index(op.f('ix_kpi_records_startup_id'), 'kpi_records', ['startup_id'], unique=False)
    op.create_table('mentoring_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('mentor_id', sa.Uuid(), nullable=True),
    sa.Column('mentor_name', sa.String(length=100), nullable=False),
    sa.Column('mentor_type', sa.String(length=50), nullable=False),
    sa.Column('session_date', sa.DateTime(), nullable=False),
    sa.Column('pre_agenda', sa.Text(), nullable=True),
    sa.Column('discussion_summary', sa.Text(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('action_items', sa.JSON(), nullable=False),
    sa.Column('next_session_date', sa.Date(), nullable=True),
    sa.Column('action_completion_rate', sa.Float(), nullable=True),
    sa.Column('improvement_notes', sa.Text(), nullable=True),
    sa.Column('pm_confirmed_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], ),
    sa.ForeignKeyConstraint(['pm_confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentoring_sessions_startup_id'), 'mentoring_sessions', ['startup_id'], unique=False)
    op.create_table('poc_projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('partner_demand_id', sa.Uuid(), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('validation_metrics', sa.JSON(), nullable=False),
    sa.Column('cost_structure', sa.Text(), nullable=True),
    sa.Column('data_scope', sa.Text(), nullable=True),
    sa.Column('success_criteria', sa.Text(), nullable=False),
    sa.Column('next_step_if_success', sa.Text(), nullable=True),
    sa.Column('participants', sa.JSON(), nullable=True),
    sa.Column('role_division', sa.Text(), nullable=True),
    sa.Column('provided_resources', sa.Text(), nullable=True),
    sa.Column('key_risks', sa.JSON(), nullable=True),
    sa.Column('status', pocstatus, nullable=False),
    sa.Column('kickoff_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('weekly_issues', sa.Text(), nullable=True),
    sa.Column('support_needed', sa.Text(), nullable=True),
    sa.Column('partner_feedback', sa.Text(), nullable=True),
    sa.Column('startup_feedback', sa.Text(), nullable=True),
    sa.Column('conversion_likelihood', sa.String(length=20), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partner_demand_id'], ['partner_demands.id'], ),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poc_projects_partner_demand_id'), 'poc_projects', ['partner_demand_id'], unique=False)
    op.create_index(op.f('ix_poc_projects_startup_id'), 'poc_projects', ['startup_id'], unique=False)
    op.create_table('sop_executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sop_template_id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=True),
    sa.Column('initiated_by', sa.Uuid(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('step_statuses', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sop_template_id'], ['sop_templates.id'], ),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment_contracts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('ic_decision_id', sa.Uuid(), nullable=False),
    sa.Column('status', contractstatus, nullable=False),
    sa.Column('investment_amount', sa.Integer(), nullable=False),
    sa.Column('pre_money_valuation', sa.Integer(), nullable=False),
    sa.Column('equity_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('vehicle', investmentvehicle, nullable=False),
    sa.Column('follow_on_rights', sa.Boolean(), nullable=False),
    sa.Column('information_rights', sa.Boolean(), nullable=False),
    sa.Column('lockup_months', sa.Integer(), nullable=True),
    sa.Column('reverse_vesting', sa.Boolean(), nullable=False),
    sa.Column('conditions_precedent', sa.JSON(), nullable=True),
    sa.Column('representations_warranties', sa.Text(), nullable=True),
    sa.Column('termsheet_doc_id', sa.String(length=100), nullable=True),
    sa.Column('sha_doc_id', sa.String(length=100), nullable=True),
    sa.Column('sha_agreement_doc_id', sa.String(length=100), nullable=True),
    sa.Column('articles_amendment_doc_id', sa.String(length=100), nullable=True),
    sa.Column('board_minutes_doc_id', sa.String(length=100), nullable=True),
    sa.Column('closing_checklist', sa.JSON(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ic_decision_id'], ['ic_decisions.id'], ),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_contracts_startup_id'), 'investment_contracts', ['startup_id'], unique=False)
    op.create_table('fund_investments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fund_id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('invested_at', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['investment_contracts.id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_investments_fund_id'), 'fund_investments', ['fund_id'], unique=False)
    op.create_index(op.f('ix_fund_investments_startup_id'), 'fund_investments', ['startup_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fund_investments_startup_id'), table_name='fund_investments')
    op.drop_index(op.f('ix_fund_investments_fund_id'), table_name='fund_investments')
    op.drop_table('fund_investments')
    op.drop_index(op.f('ix_investment_contracts_startup_id'), table_name='investment_contracts')
    op.drop_table('investment_contracts')
    op.drop_table('sop_executions')
    op.drop_index(op.f('ix_poc_projects_startup_id'), table_name='poc_projects')
    op.drop_index(op.f('ix_poc_projects_partner_demand_id'), table_name='poc_projects')
    op.drop_table('poc_projects')
    op.drop_index(op.f('ix_mentoring_sessions_startup_id'), table_name='mentoring_sessions')
    op.drop_table('mentoring_sessions')
    op.drop_index(op.f('ix_kpi_records_startup_id'), table_name='kpi_records')
    op.drop_table('kpi_records')
    op.drop_index(op.f('ix_investor_meetings_startup_id'), table_name='investor_meetings')
    op.drop_table('investor_meetings')
    op.drop_index(op.f('ix_incubations_startup_id'), table_name='incubations')
    op.drop_table('incubations')
    op.drop_index(op.f('ix_government_programs_startup_id'), table_name='government_programs')
    op.drop_table('government_programs')
    op.drop_table('form_submissions')
    op.drop_index(op.f('ix_follow_on_investments_startup_id'), table_name='follow_on_investments')
    op.drop_table('follow_on_investments')
    op.drop_index(op.f('ix_exit_records_startup_id'), table_name='exit_records')
    op.drop_table('exit_records')
    op.drop_index(op.f('ix_cap_table_entries_startup_id'), table_name='cap_table_entries')
    op.drop_table('cap_table_entries')
    op.drop_table('team_kpis')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_fund_lps_fund_id'), table_name='fund_lps')
    op.drop_table('fund_lps')
    op.drop_table('demo_days')
    op.drop_table('sop_templates')
    op.drop_table('partner_demands')
    op.drop_table('job_descriptions')
    op.drop_table('funds')
    op.drop_table('form_templates')
    # ### end Alembic commands ###
