"""phase3_review_memo_ic

Revision ID: bccabceb7251
Revises: c080814c28b8
Create Date: 2026-03-16 23:11:47.739569
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bccabceb7251'
down_revision: Union[str, None] = 'c080814c28b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_memos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('overview', sa.Text(), nullable=False),
    sa.Column('team_assessment', sa.Text(), nullable=False),
    sa.Column('market_assessment', sa.Text(), nullable=False),
    sa.Column('tech_product_assessment', sa.Text(), nullable=False),
    sa.Column('traction', sa.Text(), nullable=False),
    sa.Column('risks', sa.Text(), nullable=False),
    sa.Column('value_add_points', sa.Text(), nullable=False),
    sa.Column('proposed_terms', sa.JSON(), nullable=False),
    sa.Column('post_investment_plan', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_memos_startup_id'), 'investment_memos', ['startup_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('review_type', sa.String(length=20), nullable=False),
    sa.Column('team_score', sa.Integer(), nullable=True),
    sa.Column('problem_score', sa.Integer(), nullable=True),
    sa.Column('solution_score', sa.Integer(), nullable=True),
    sa.Column('market_score', sa.Integer(), nullable=True),
    sa.Column('traction_score', sa.Integer(), nullable=True),
    sa.Column('number_literacy', sa.Integer(), nullable=True),
    sa.Column('customer_experience', sa.Integer(), nullable=True),
    sa.Column('tech_moat', sa.Integer(), nullable=True),
    sa.Column('execution_plan', sa.Integer(), nullable=True),
    sa.Column('feedback_absorption', sa.Integer(), nullable=True),
    sa.Column('cofounder_stability', sa.Integer(), nullable=True),
    sa.Column('dd_checklist', sa.JSON(), nullable=True),
    sa.Column('risk_log', sa.Text(), nullable=True),
    sa.Column('overall_verdict', sa.String(length=20), nullable=False),
    sa.Column('tech_type', sa.String(length=30), nullable=True),
    sa.Column('scalability_score', sa.Integer(), nullable=True),
    sa.Column('process_compatibility', sa.Integer(), nullable=True),
    sa.Column('sample_test_status', sa.String(length=30), nullable=True),
    sa.Column('certification_stage', sa.String(length=100), nullable=True),
    sa.Column('purchase_lead_time_months', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_startup_id'), 'reviews', ['startup_id'], unique=False)
    op.create_table('ic_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('memo_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'CONDITIONAL', 'ON_HOLD', 'INCUBATION_FIRST', 'REJECTED', name='icdecisiontype'), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('monitoring_points', sa.Text(), nullable=True),
    sa.Column('attendees', sa.JSON(), nullable=False),
    sa.Column('contract_assignee_id', sa.Uuid(), nullable=True),
    sa.Column('program_assignee_id', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contract_assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['memo_id'], ['investment_memos.id'], ),
    sa.ForeignKeyConstraint(['program_assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ic_decisions_startup_id'), 'ic_decisions', ['startup_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ic_decisions_startup_id'), table_name='ic_decisions')
    op.drop_table('ic_decisions')
    op.drop_index(op.f('ix_reviews_startup_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_investment_memos_startup_id'), table_name='investment_memos')
    op.drop_table('investment_memos')
    # ### end Alembic commands ###
