"""phase2_screening_handover

Revision ID: c080814c28b8
Revises: c9a0557e61d1
Create Date: 2026-03-16 22:18:07.010910
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c080814c28b8'
down_revision: Union[str, None] = 'c9a0557e61d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handover_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('from_team', sa.String(length=50), nullable=False),
    sa.Column('to_team', sa.String(length=50), nullable=False),
    sa.Column('handover_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_by', sa.Uuid(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handover_documents_startup_id'), 'handover_documents', ['startup_id'], unique=False)
    op.create_table('screenings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('screener_id', sa.Uuid(), nullable=False),
    sa.Column('fulltime_commitment', sa.Integer(), nullable=False),
    sa.Column('problem_clarity', sa.Integer(), nullable=False),
    sa.Column('tech_differentiation', sa.Integer(), nullable=False),
    sa.Column('market_potential', sa.Integer(), nullable=False),
    sa.Column('initial_validation', sa.Integer(), nullable=False),
    sa.Column('legal_clear', sa.Boolean(), nullable=False),
    sa.Column('strategy_fit', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.String(length=20), nullable=False),
    sa.Column('risk_notes', sa.Text(), nullable=True),
    sa.Column('handover_memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['screener_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screenings_startup_id'), 'screenings', ['startup_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screenings_startup_id'), table_name='screenings')
    op.drop_table('screenings')
    op.drop_index(op.f('ix_handover_documents_startup_id'), table_name='handover_documents')
    op.drop_table('handover_documents')
    # ### end Alembic commands ###
