"""phase1_core_models_8_tables

Revision ID: c9a0557e61d1
Revises: 
Create Date: 2026-03-16 19:54:23.599486
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9a0557e61d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_name', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('recruitment_start', sa.Date(), nullable=False),
    sa.Column('recruitment_end', sa.Date(), nullable=False),
    sa.Column('program_start', sa.Date(), nullable=False),
    sa.Column('program_end', sa.Date(), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('selected_count', sa.Integer(), nullable=False),
    sa.Column('demo_day_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_name')
    )
    op.create_table('mentors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('mentor_type', sa.String(length=50), nullable=False),
    sa.Column('expertise_areas', sa.JSON(), nullable=False),
    sa.Column('industry_tags', sa.JSON(), nullable=True),
    sa.Column('functional_area', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('availability', sa.String(length=100), nullable=True),
    sa.Column('engagement_count', sa.Integer(), nullable=False),
    sa.Column('avg_satisfaction', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('team', sa.String(length=50), nullable=False),
    sa.Column('role_title', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.Enum('HANDOVER_REQUEST', 'DEADLINE_ALERT', 'IC_SCHEDULE', 'KPI_WARNING', 'REPORT_DEADLINE', 'CRISIS_ALERT', 'ESCALATION', 'CONTRACT_OVERDUE', name='notificationtype'), nullable=False),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.Uuid(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('organization_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_settings_key'), 'organization_settings', ['key'], unique=True)
    op.create_table('startups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('corporate_number', sa.String(length=50), nullable=True),
    sa.Column('ceo_name', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('one_liner', sa.String(length=500), nullable=False),
    sa.Column('problem_definition', sa.Text(), nullable=True),
    sa.Column('solution_description', sa.Text(), nullable=True),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('is_fulltime', sa.Boolean(), nullable=False),
    sa.Column('sourcing_channel', sa.Enum('UNIVERSITY_LAB', 'CORPORATE_OI', 'PORTFOLIO_REFERRAL', 'VC_CVC_ANGEL', 'PUBLIC_PROGRAM', 'COMPETITION_FORUM', 'ONLINE_APPLICATION', 'DIRECT_OUTREACH', 'TECH_EXPO', name='sourcingchannel'), nullable=False),
    sa.Column('referrer', sa.String(length=200), nullable=True),
    sa.Column('current_deal_stage', sa.Enum('INBOUND', 'FIRST_SCREENING', 'DEEP_REVIEW', 'INTERVIEW', 'DUE_DILIGENCE', 'IC_PENDING', 'IC_REVIEW', 'APPROVED', 'CONDITIONAL', 'ON_HOLD', 'INCUBATION_FIRST', 'REJECTED', 'CONTRACT', 'CLOSED', 'PORTFOLIO', name='dealstage'), nullable=False),
    sa.Column('portfolio_grade', sa.Enum('A', 'B', 'C', 'D', name='portfoliograde'), nullable=True),
    sa.Column('is_portfolio', sa.Boolean(), nullable=False),
    sa.Column('founded_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('main_customer', sa.String(length=500), nullable=True),
    sa.Column('current_traction', sa.Text(), nullable=True),
    sa.Column('current_revenue', sa.Integer(), nullable=True),
    sa.Column('current_employees', sa.Integer(), nullable=True),
    sa.Column('first_meeting_date', sa.Date(), nullable=True),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_manager_id', sa.Uuid(), nullable=True),
    sa.Column('invested_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_startup_id'), 'activity_logs', ['startup_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('deal_flows',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.Enum('INBOUND', 'FIRST_SCREENING', 'DEEP_REVIEW', 'INTERVIEW', 'DUE_DILIGENCE', 'IC_PENDING', 'IC_REVIEW', 'APPROVED', 'CONDITIONAL', 'ON_HOLD', 'INCUBATION_FIRST', 'REJECTED', 'CONTRACT', 'CLOSED', 'PORTFOLIO', name='dealstage'), nullable=False),
    sa.Column('moved_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('moved_by', sa.Uuid(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['moved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_flows_startup_id'), 'deal_flows', ['startup_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deal_flows_startup_id'), table_name='deal_flows')
    op.drop_table('deal_flows')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_startup_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_table('startups')
    op.drop_index(op.f('ix_organization_settings_key'), table_name='organization_settings')
    op.drop_table('organization_settings')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('mentors')
    op.drop_table('batches')
    # ### end Alembic commands ###
